### ISSUE TITLE
Создание объявления

### ISSUE THREAD

**Issue by mokujin90** [mokujin90/mistress#1]
Создание объявления на доставку / отправку.

В случае "отвезу посылку" возможен выбор маршрута с N-кол-вом мест.
Для "доставте посылку" Откуда - куда. (2 места) - (пока что так).

Для выбора мест используем гугл карту. ориентируемся на эту форму https://dostavista.ru/order?standard

Ссылка на тему http://templatecycle.com/demo/bootclassified/
Создание объявления http://templatecycle.com/demo/bootclassified/post-ads.html
ЛК юзера http://templatecycle.com/demo/bootclassified/account-home.html

**Comment by mokujin90** [comment]
Не давать создавать объявление с пустыми направлениями.
При выборе "Готов передать посылку" заголовки "откуда" дублируются.
При выборе "Готов передать посылку" - можно много адресов добавлять, а не наоборот.
Все направления записываются в базу как "from". поэтому не выводятся в редактировании.
Поля вес, цена относятся к заказу в целом, почему в destination?

**Comment by multeg** [comment]
:beginner:
